version: "3.9"
services:
  my_cve:
    volumes:
      - type: volume
        source: share/
        target: /share
        volume:
          nocopy: true
    image: hahaleyile/my-cve-2021-1675
    tty: true
    ports:
      - "445:445"
